### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by dekillxsin** [r1emu/R1EMU#31]
title^^^^

**Comment by Spl3en** [comment]
Hi,

It is not currently, as you can see there is no commit since few months.
However, things may change for the IOBT release :)

**Comment by marclfv** [comment]
I looked at the script and some items are outdated.

The Melia appears to be more current than R1emu. ^^

**Comment by Spl3en** [comment]
Melia seems far more advanced than R1EMU currently. If you want an updated server emulator, you should look at it once it goes open source.

**Comment by marclfv** [comment]
@Spl3en

**Comment by marclfv** [comment]
@Spl3en 
I would like to apologize if you understood me wrong. OR melia not yet released the emulator.
I just wanted to point out that the R1Emu this outdated. And we do not know if there is still work on the emulator

**Comment by Spl3en** [comment]
Yes, R1EMU is outdated, and probably need a lot of refactoring.
The project isn't maintained anymore, I'll consider working on it again after Melia's release
